/**
 * NOTE: This data is not strictly necessary for the assignment, 
 * but was generated by ChatGPT and included because it will **likely** be helpful.
 * Feel free to modify, ignore or expand it as needed.
 */

const Genres = {
    ACTION: "Action",
    ADVENTURE: "Adventure",
    RPG: "Role-Playing Game",
    FPS: "First-Person Shooter",
    STRATEGY: "Strategy",
    SPORTS: "Sports",
    HORROR: "Horror",
    SIMULATION: "Simulation",
    PUZZLE: "Puzzle",
    RACING: "Racing"
};

const VideoGames = [
    {
        id: 1,
        title: "The Legend of Zelda: Breath of the Wild",
        releaseYear: 2017,
        averageRating: 9.8,
        numberOfReviews: 950,
        description: "An open-world adventure set in Hyrule.",
        img: "https://upload.wikimedia.org/wikipedia/en/0/02/The_Legend_of_Zelda_Breath_of_the_Wild.jpg"
    },
    {
        id: 2,
        title: "The Witcher 3: Wild Hunt",
        releaseYear: 2015,
        averageRating: 9.7,
        numberOfReviews: 15000,
        description: "A sprawling RPG filled with monsters, magic, and rich storytelling.",
        img: "https://upload.wikimedia.org/wikipedia/en/0/0c/Witcher_3_cover_art.jpg"
    },
    {
        id: 3,
        title: "Half-Life 2",
        releaseYear: 2004,
        averageRating: 9.6,
        numberOfReviews: 10000,
        description: "A groundbreaking first-person shooter with physics-based gameplay.",
        img: "https://upload.wikimedia.org/wikipedia/en/2/25/Half-Life_2_cover.jpg"
    },
    {
        id: 4,
        title: "Dark Souls III",
        releaseYear: 2016,
        averageRating: 9.4,
        numberOfReviews: 8500,
        description: "A brutally challenging RPG with rich lore and deep combat.",
        img: "https://upload.wikimedia.org/wikipedia/en/1/16/Dark_Souls_III_cover_art.jpg"
    },
    {
        id: 5,
        title: "Minecraft",
        releaseYear: 2011,
        averageRating: 9.5,
        numberOfReviews: 20000,
        description: "A sandbox game where you can build and explore infinite worlds.",
        img: "https://upload.wikimedia.org/wikipedia/en/5/51/Minecraft_cover.png"
    },
    {
        id: 6,
        title: "Celeste",
        releaseYear: 2018,
        averageRating: 9.5,
        numberOfReviews: 800,
        description: "A heartfelt platformer about climbing a mountain while overcoming personal struggles.",
        img: "https://upload.wikimedia.org/wikipedia/en/6/69/Celeste_box_art_final.png"
    },
    {
        id: 7,
        title: "Hollow Knight",
        releaseYear: 2017,
        averageRating: 9.5,
        numberOfReviews: 7500,
        description: "A hand-drawn Metroidvania with deep exploration and tight combat.",
        img: "https://upload.wikimedia.org/wikipedia/en/1/11/Hollow_Knight_first_cover_art.jpg"
    },
    {
        id: 8,
        title: "Katana ZERO",
        releaseYear: 2019,
        averageRating: 9.0,
        numberOfReviews: 600,
        description: "A stylish neo-noir action-platformer with fast-paced combat.",
        img: "https://upload.wikimedia.org/wikipedia/en/2/2b/Katana_Zero_cover_art.jpg"
    },
    {
        id: 9,
        title: "Outer Wilds",
        releaseYear: 2019,
        averageRating: 9.3,
        numberOfReviews: 900,
        description: "A mystery exploration game set in a solar system trapped in a time loop.",
        img: "https://upload.wikimedia.org/wikipedia/en/4/4a/Outer_Wilds_cover_art.jpg"
    },
    {
        id: 10,
        title: "Disco Elysium",
        releaseYear: 2019,
        averageRating: 9.6,
        numberOfReviews: 950,
        description: "A narrative-driven RPG where you play as a detective with unique skill-based dialogue.",
        img: "https://upload.wikimedia.org/wikipedia/en/8/8b/Disco_Elysium_cover_art.jpg"
    }
    // ... other games
];

module.exports = { VideoGames };
